config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  resources :characters, only: [:show, :new, :create, :index] do
    resources :obligations, only: [:new, :create]
  end
  resources :battles, only: [:new, :create, :index, :show] do
    resources :obligations, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/battle.rb
class Battle < ApplicationRecord
  has_many :characters, through: :obligations
  has_many :obligations
  validates :title, :fight_date, :location, presence: true
  has_one_attached :photo
end

app/models/character.rb
class Character < ApplicationRecord
  has_many :battles, through: :obligations
  has_many :obligations
  has_one_attached :photo
  validates :name, :age, :ranking, presence: true
  validates :name, uniqueness: true
end

app/models/obligation.rb
class Obligation < ApplicationRecord
  belongs_to :character
  belongs_to :battle
  validates :character_id, uniqueness: {
    scope: [:battle_id]
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/battles_controller.rb
class BattlesController < ApplicationController
  def index
    @battles = Battle.all
  end

  def show
    @battle = Battle.find(params[:id])
  end

  def new
    @battle = Battle.new
  end

  def create
    @battle = Battle.new(battle_params)
    if @battle.save
      redirect_to battle_path(@battle)
    else
      render :new, status: unprocessable_entity
    end
  end

  private

  def battle_params
    params.require(:battle).permit(:title, :fight_date, :location, :result, :photo)
  end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController

  def index
    @characters = Character.all
  end

  def show
    @character = Character.find(params[:id])
    @obligations = @character.obligations
  end

  def new
    @character = Character.new
  end

  def create
    @character = Character.new(character_params)
    if @character.save
      redirect_to character_path(@character)
    else
      render :new, status: unprocessable_entity
    end
  end

  def character_params
    params.require(:character).permit(:name, :age, :ranking, :bio, :photo)
  end
end

app/controllers/obligations_controller.rb
class ObligationsController < ApplicationController
  before_action :set_character, only: %i[new create]

  def new
    @obligation = Obligation.new
  end

  def create
    @obligation = Obligation.new(obligation_params)
    @obligation.character = @character
    if @obligation.save
      redirect_to character_path(@character)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_character
    @character = Character.find(params[:character_id])
  end

  def obligation_params
    params.require(:obligation).permit(:character_id, :battle_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/battles/index.html.erb
<div class="banner banner-alt" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://www.aiatucson.arizona.edu/sites/aiatucson.arizona.edu/files/Alexander%20Mosaic.jpg);">
  <div class="container">
    <h1>Battles</h1>
    <h3>We must all do battle someday!</h3>
    <%= link_to "MAKE BATTLE", new_battle_path, class: 'btn btn-danger mt-3'%>
  </div>
</div>
<div class="container">
  <div class="cards">
    <% @battles.each do |battle| %>
      <%= link_to battle_path(battle) do %>
        <div class="card-category zoom" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= battle.photo.attached? ? cl_image_path(battle.photo.key,crop: :thumb,gravity: :face) : 'http://source.unsplash.com/featured/?battle' %>)">
          <%= battle.title %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/battles/new.html.erb
<div class="text-center form-styles">
  <h1>New Battle</h1>
  <p>Where is the next battle at?</p>
</div>
<div class="container form-styles">
  <%= simple_form_for(@battle) do |f| %>
    <%= f.input :title %>
    <%= f.input :fight_date %>
    <%= f.input :location %>
    <%= f.input :photo, as: :file %>
    <%= f.submit class: 'btn btn-primary mt-3' %>
  <% end %>
</div>

app/views/battles/show.html.erb
<head>
  <link href="https://api.mapbox.com/mapbox-gl-js/v1.11.1/mapbox-gl.css" rel="stylesheet">
</head>
<div class="container text-center">
  <div class="flex-card d-flex flex-column justify-items-center">
    <h1><%= @battle.title%></h1>
    <h3><%= @battle.fight_date %></h3>
    <p><%= @battle.location %></p>
    <div class="container form-submission" data-controller="get-all-addresses">
      <form>
        <input class="form-control" type="hidden" id="custId" name="custId" value=<%=@battle.location%> data-get-all-addresses-target="address">
        <input class="map-form-btn" type="submit" value="Show location" class="btn btn-primary" data-action="click->get-all-addresses#geocodeSubmit">
      </form>
      <div id="map" style="height: 300px; width: 600px">
        <!-- Display the map in this div -->
      </div>
    </div>
  </div>
</div>
</div>
</div>
<div class="text-center">
  <h2>Participants</h2>
</div>
<div class="container">
  <div class="cards">
    <% @battle.obligations.each do |obligation| %>
      <div class="card-category zoom" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= obligation.character.photo.attached? ? cl_image_path(obligation.character.photo.key,crop: :thumb,gravity: :face) : 'http://source.unsplash.com/featured/?warrior' %>)">
        <%= obligation.character.name %>
      </div>
    <% end %>
  </div>
</div>

app/views/characters/index.html.erb
<div class="banner banner-alt" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(http://cdn.shopify.com/s/files/1/1551/9675/articles/Ancient_Roman_Bust_Sculpture-for_blog.jpg?v=1506020550);">
  <div class="container">
    <h1>Characters</h1>
    <h3>Add your favourite to the list!</h3>
    <%= link_to "MAKE CHARACTER", new_character_path, class: 'btn btn-primary mt-3'%>
  </div>
</div>


<div class="container">
  <div class="cards">
    <% @characters.each do |character| %>
      <%= link_to character_path(character) do %>
        <div class="card-category zoom" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= character.photo.attached? ? cl_image_path(character.photo.key,crop: :thumb,gravity: :face) : 'http://source.unsplash.com/featured/?warrior' %>)">
          <%= character.name %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/characters/new.html.erb
<div class="text-center form-styles">
  <h1>New Character</h1>
  <p>Who will you add to join the fight?</p>
</div>
<div class="container form-styles">
  <%= simple_form_for(@character) do |f| %>
    <%= f.input :name %>
    <%= f.input :age %>
    <%= f.input :ranking %>
    <%= f.input :bio %>
    <%= f.input :photo, as: :file %>
    <%= f.submit class: 'btn btn-primary mt-3' %>
  <% end %>
</div>

app/views/characters/show.html.erb
<div class="container">
  <div class="d-flex justify-content-center">
    <div class="flip-card">
      <div class="flip-card-inner">
        <div class="flip-card-front">
          <%= image_tag @character.photo.attached? ? cl_image_path(@character.photo.key,width: 400 ,height: 600,crop: :thumb,gravity: :face) : 'http://source.unsplash.com/featured/?warrior'%>
        </div>
        <div class="flip-card-back">
          <h1><%= @character.name%></h1>
          <h3>Age:</h3>
          <p><%= @character.age %></p>
          <h3>Ranking:</h3>
          <p><%= @character.ranking%></p>
          <h3>Bio:</h3>
          <p><%= @character.bio %></p>
          <%= link_to "Create new obligation", new_character_obligation_path(@character), class: 'btn btn-primary mt-3' %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="text-center">
  <h2>Battles!</h2>
</div>
<div class="container">
  <div class="cards">
    <% @character.obligations.each do |obligation| %>
      <div class="card-category zoom" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= obligation.battle.photo.attached? ? cl_image_path(obligation.battle.photo.key,crop: :thumb,gravity: :face) : 'http://source.unsplash.com/featured/?warrior' %>)">
        <%= obligation.battle.title %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SuperBattleKnight</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v1.11.1/mapbox-gl.css" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/obligations/new.html.erb
<div class="text-center form-styles">
  <h1>New Obligation</h1>
  <p>Who will join the fight and help in battle!</p>
</div>
<div class="container form-styles">
  <%= simple_form_for [@character, @obligation] do |f| %>
    <%= f.association :character %>
    <%= f.association :battle %>
    <%= f.submit class: 'btn btn-primary mt-3' %>
  <% end %>
</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://preview.redd.it/vamnszp5g1d21.jpg?auto=webp&amp;s=27571716fa09885563535c8b0262ed22784413e0);">
  <div class="container">
    <h1>Super Battle Knight</h1>
    <h3><span data-controller="typed-js"></span></h3>
  </div>
</div>
<div class="container">
  <div class="d-flex justify-content-around">
    <%= link_to characters_path do %>
      <div class="card-category zoom" style="background-image: linear-gradient(rgba(0,0,0,0.8), rgba(0,0,0,0.6)), url(https://cdna.artstation.com/p/assets/images/images/009/255/062/large/woong-bae-byun-knight.jpg?1517954885)">
        Characters
      </div>
    <% end %>
    <%= link_to battles_path do %>
      <div class="card-category zoom" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://media.istockphoto.com/photos/medieval-battle-scene-with-cavalry-and-infantry-silhouettes-of-as-picture-id924589584?k=20&amp;m=924589584&amp;s=612x612&amp;w=0&amp;h=qIly_DWt5LUzHBaoOgOaVPnqQx9jh9C3VszDw6bReEQ=)">
        Battles
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://github.com/billcookie"><i class="fab fa-github"></i></a>
    <a href="https://instagram.com/billcookie"><i class="fab fa-instagram"></i></a>
    <a href="https://twitter.com/billcookiez"><i class="fab fa-twitter"></i></a>
    <a href="https://www.linkedin.com/in/bill--cook/"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Follow us on social media!
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <span><i class="fa-solid fa-khanda"></i></span>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Characters", characters_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Battles", battles_path, class: "nav-link" %>
        </li>
          </div>
        </li>
      </ul>
    </div>
  </div>
</div>